server {
    listen 80;

    location = / {
        return 301 /quit_assessments/;
    }

    location /quit_assessments/ {
        alias /usr/share/nginx/html/quit_assessments/;
        index index.html;
        try_files $uri $uri/ /quit_assessments/index.html;
    }

    error_page 404 /quit_assessments/index.html;
}
